[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "dextrademixer"
version = "0.0.1"
description = "Probabilistic identification of antigen-specific T cells from single-cell pMHC multimer data"
readme = "README.md"
requires-python = ">=3.12"
license = "BSD-3-Clause"
authors = [
  { name = "Yang an", email = "yang.an@helmholtz-muenchen.de" },
  { name = "Benjamin Schubert", email = "benjamin.schubert@helmholtz-muenchen.de" }
]
maintainers = [
  {name = "Yang an", email = "yang.an@helmholtz-muenchen.de" },
  { name = "Benjamin Schubert", email = "benjamin.schubert@helmholtz-muenchen.de" },
]
keywords = [
  "antigen specificity",
  "pMHC multimer",
  "single-cell",
  "T cell",
]
classifiers = [
  "Development Status :: 3 - Beta",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
  "anndata==0.13.2",
  "arviz==0.22.0",
  "jax==0.8.1",
  "jaxlib==0.8.1",
  "matplotlib==3.10.7",
  "mudata==0.3.2",
  "muon==0.1.7",
  "numpy==2.3.5",
  "numpyro==0.19.0",
  "openpyxl>=3.1.5",
  "optax==0.2.6",
  "pandas==2.3.3",
  "psutil==7.1.3",
  "scanpy==1.11.5",
  "scikit-learn==1.7.2",
  "scipy==1.16.3",
  "scirpy==0.22.3",
  "seaborn==0.13.2",
  "statsmodels==0.14.5",
  "tcrdist3==0.3",
  "tqdm==4.70.0",
]

[project.urls]
Homepage = "https://github.com/SchubertLab/DextraDemixer"
Issues = "https://github.com/SchubertLab/DextraDemixer/issues"
Publication = "https://doi.org/10.64898/2026.06.23.733339"
Repository = "https://github.com/SchubertLab/DextraDemixer.git"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["dextrademixer*"]
exclude = ["dextrademixer.test*"]

